import { Link } from "@tanstack/react-router";
import { ArrowUpRight, Download, Plus, Search, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type OperationsPageProps = { title: string; eyebrow: string; description: string; route: string; metrics: { label: string; value: string; detail: string }[]; columns: string[]; rows: string[][]; actions?: string[]; related?: { label: string; to: string }[]; note?: string };

export function OperationsPage({ title, eyebrow, description, metrics, columns, rows, actions = ["Add record", "Export"], related = [], note }: OperationsPageProps) {
  return <div className="container-page py-10">
    <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold tracking-[0.22em] uppercase text-gold">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-primary md:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div><div className="flex flex-wrap gap-2">{actions.map((action, i) => <Button key={action} variant={i === 0 ? "default" : "outline"}><>{i === 0 ? <Plus data-icon="inline-start" /> : <Download data-icon="inline-start" />}</>{action}</Button>)}</div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map((metric) => <div key={metric.label} className="rounded-2xl border bg-card p-5 shadow-sm"><p className="text-sm text-muted-foreground">{metric.label}</p><p className="mt-2 text-3xl font-semibold text-primary">{metric.value}</p><p className="mt-1 text-xs text-muted-foreground">{metric.detail}</p></div>)}</div>
    <div className="mt-8 rounded-2xl border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold">Records</h2><p className="mt-1 text-sm text-muted-foreground">Search, filter, sort and review authorised school records.</p></div><div className="relative w-full sm:w-80"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><Input className="pl-9" placeholder="Search records" aria-label="Search records" /></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-muted-foreground"><tr>{columns.map((column) => <th key={column} className="px-3 py-3 font-medium">{column}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row, index) => <tr key={index} className="transition hover:bg-muted/40">{row.map((cell, cellIndex) => <td key={cellIndex} className="px-3 py-4">{cellIndex === row.length - 1 ? <Badge variant="secondary">{cell}</Badge> : cell}</td>)}</tr>)}</tbody></table></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t pt-4 text-xs text-muted-foreground"><span>Showing {rows.length} sample records</span><div className="flex gap-2"><Button size="sm" variant="outline">Previous</Button><Button size="sm" variant="outline">Next</Button></div></div></div>
    {note && <div className="mt-6 rounded-2xl border border-gold/30 bg-gold/5 p-5 text-sm leading-6 text-muted-foreground"><ShieldCheck className="mr-2 inline size-4 text-gold" aria-hidden="true" />{note}</div>}
    {related.length > 0 && <div className="mt-8 flex flex-wrap gap-3" aria-label="Related pages">{related.map((item) => <Button asChild key={item.to} variant="outline"><Link to={item.to}>{item.label}<ArrowUpRight data-icon="inline-end" /></Link></Button>)}</div>}
  </div>;
}

export const sampleRows = { students: [["CRA-2026-0001 · Tendai Moyo", "Form 2A", "Guardian verified", "96%", "Active"], ["CRA-2026-0002 · Rudo Chirwa", "Form 3B", "Guardian verified", "91%", "Active"], ["CRA-2026-0003 · Kudzai Ncube", "Form 1C", "Follow-up required", "79%", "Needs support"]], admissions: [["CRA-APP-1042 · Tariro Moyo", "Form 1", "Hillcrest Primary", "12 Sep 2026", "Under review"], ["CRA-APP-1041 · Farai Dube", "Form 3", "Mufakose High", "11 Sep 2026", "Accepted"], ["CRA-APP-1038 · Nyasha Ncube", "Form 2", "Glenview Primary", "09 Sep 2026", "Waitlisted"]], payments: [["RCT-0264", "Tendai Moyo", "$420", "EcoCash", "16 Sep 2026", "Posted"], ["RCT-0263", "Rudo Chirwa", "$380", "Bank transfer", "15 Sep 2026", "Posted"], ["RCT-0262", "Kudzai Ncube", "$200", "Cash", "15 Sep 2026", "Pending allocation"]] };

export function pageMeta(title: string) { return { meta: [{ title: `${title} - Cresta Reign Academy` }, { name: "robots", content: "noindex" }] }; }

