/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicAcademicsRouteImport } from './routes/_public.academics'
import { Route as PublicAdmissionsRouteImport } from './routes/_public.admissions'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicEventsRouteImport } from './routes/_public.events'
import { Route as PublicGalleryRouteImport } from './routes/_public.gallery'
import { Route as PublicHelpRouteImport } from './routes/_public.help'
import { Route as PublicNewsRouteImport } from './routes/_public.news'
import { Route as PublicStaffRouteImport } from './routes/_public.staff'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAcademicsRouteImport } from './routes/admin.academics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminArchitectureRouteImport } from './routes/admin.architecture'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminCommunicationRouteImport } from './routes/admin.communication'
import { Route as AdminDisciplineRouteImport } from './routes/admin.discipline'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminGovernanceRouteImport } from './routes/admin.governance'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminProcurementRouteImport } from './routes/admin.procurement'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as PublicEventsSlugRouteImport } from './routes/_public.events.$slug'
import { Route as PublicGallerySlugRouteImport } from './routes/_public.gallery.$slug'
import { Route as PublicNewsSlugRouteImport } from './routes/_public.news.$slug'
import { Route as AdminAdmissionsIndexRouteImport } from './routes/admin.admissions.index'
import { Route as AdminAdmissionsIdRouteImport } from './routes/admin.admissions.$id'
import { Route as AdminAdmissionsSettingsRouteImport } from './routes/admin.admissions.settings'
import { Route as AdminFinancePaymentsRouteImport } from './routes/admin.finance.payments'
import { Route as AdminSecurityVisitorsRouteImport } from './routes/admin.security.visitors'
import { Route as ApplyApplicationIdRouteImport } from './routes/apply.application.$id'
import { Route as ApplyStatusIdRouteImport } from './routes/apply.status.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAcademicsRoute = PublicAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAdmissionsRoute = PublicAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHelpRoute = PublicHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsRoute = PublicNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStaffRoute = PublicStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicsRoute = AdminAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArchitectureRoute = AdminArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationRoute = AdminCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisciplineRoute = AdminDisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGovernanceRoute = AdminGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcurementRoute = AdminProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRoute,
} as any)
const PublicEventsSlugRoute = PublicEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicEventsRoute,
} as any)
const PublicGallerySlugRoute = PublicGallerySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicGalleryRoute,
} as any)
const PublicNewsSlugRoute = PublicNewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicNewsRoute,
} as any)
const AdminAdmissionsIndexRoute = AdminAdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsIdRoute = AdminAdmissionsIdRouteImport.update({
  id: '/admissions/$id',
  path: '/admissions/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsSettingsRoute = AdminAdmissionsSettingsRouteImport.update({
  id: '/admissions/settings',
  path: '/admissions/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancePaymentsRoute = AdminFinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminSecurityVisitorsRoute = AdminSecurityVisitorsRouteImport.update({
  id: '/security/visitors',
  path: '/security/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const ApplyApplicationIdRoute = ApplyApplicationIdRouteImport.update({
  id: '/application/$id',
  path: '/application/$id',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyStatusIdRoute = ApplyStatusIdRouteImport.update({
  id: '/status/$id',
  path: '/status/$id',
  getParentRoute: () => ApplyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/parent': typeof ParentRoute
  '/teacher': typeof TeacherRoute
  '/about': typeof PublicAboutRoute
  '/academics': typeof PublicAcademicsRoute
  '/admissions': typeof PublicAdmissionsRoute
  '/contact': typeof PublicContactRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/gallery': typeof PublicGalleryRouteWithChildren
  '/help': typeof PublicHelpRoute
  '/news': typeof PublicNewsRouteWithChildren
  '/staff': typeof PublicStaffRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/architecture': typeof AdminArchitectureRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/discipline': typeof AdminDisciplineRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/procurement': typeof AdminProcurementRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/events/$slug': typeof PublicEventsSlugRoute
  '/gallery/$slug': typeof PublicGallerySlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/admin/admissions/settings': typeof AdminAdmissionsSettingsRoute
  '/admin/finance/payments': typeof AdminFinancePaymentsRoute
  '/admin/security/visitors': typeof AdminSecurityVisitorsRoute
  '/apply/application/$id': typeof ApplyApplicationIdRoute
  '/apply/status/$id': typeof ApplyStatusIdRoute
  '/admin/admissions/': typeof AdminAdmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/parent': typeof ParentRoute
  '/teacher': typeof TeacherRoute
  '/about': typeof PublicAboutRoute
  '/academics': typeof PublicAcademicsRoute
  '/admissions': typeof PublicAdmissionsRoute
  '/contact': typeof PublicContactRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/gallery': typeof PublicGalleryRouteWithChildren
  '/help': typeof PublicHelpRoute
  '/news': typeof PublicNewsRouteWithChildren
  '/staff': typeof PublicStaffRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/architecture': typeof AdminArchitectureRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/discipline': typeof AdminDisciplineRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/procurement': typeof AdminProcurementRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/events/$slug': typeof PublicEventsSlugRoute
  '/gallery/$slug': typeof PublicGallerySlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/admin/admissions/settings': typeof AdminAdmissionsSettingsRoute
  '/admin/finance/payments': typeof AdminFinancePaymentsRoute
  '/admin/security/visitors': typeof AdminSecurityVisitorsRoute
  '/apply/application/$id': typeof ApplyApplicationIdRoute
  '/apply/status/$id': typeof ApplyStatusIdRoute
  '/admin/admissions': typeof AdminAdmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/parent': typeof ParentRoute
  '/teacher': typeof TeacherRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/academics': typeof PublicAcademicsRoute
  '/_public/admissions': typeof PublicAdmissionsRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/events': typeof PublicEventsRouteWithChildren
  '/_public/gallery': typeof PublicGalleryRouteWithChildren
  '/_public/help': typeof PublicHelpRoute
  '/_public/news': typeof PublicNewsRouteWithChildren
  '/_public/staff': typeof PublicStaffRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/architecture': typeof AdminArchitectureRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/discipline': typeof AdminDisciplineRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/governance': typeof AdminGovernanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/procurement': typeof AdminProcurementRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/_public/events/$slug': typeof PublicEventsSlugRoute
  '/_public/gallery/$slug': typeof PublicGallerySlugRoute
  '/_public/news/$slug': typeof PublicNewsSlugRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/admin/admissions/settings': typeof AdminAdmissionsSettingsRoute
  '/admin/finance/payments': typeof AdminFinancePaymentsRoute
  '/admin/security/visitors': typeof AdminSecurityVisitorsRoute
  '/apply/application/$id': typeof ApplyApplicationIdRoute
  '/apply/status/$id': typeof ApplyStatusIdRoute
  '/admin/admissions/': typeof AdminAdmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/parent'
    | '/teacher'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/help'
    | '/news'
    | '/staff'
    | '/admin/academics'
    | '/admin/ai'
    | '/admin/architecture'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/certificates'
    | '/admin/communication'
    | '/admin/discipline'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/governance'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/procurement'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/'
    | '/apply/'
    | '/events/$slug'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/admin/admissions/$id'
    | '/admin/admissions/settings'
    | '/admin/finance/payments'
    | '/admin/security/visitors'
    | '/apply/application/$id'
    | '/apply/status/$id'
    | '/admin/admissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/parent'
    | '/teacher'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/help'
    | '/news'
    | '/staff'
    | '/admin/academics'
    | '/admin/ai'
    | '/admin/architecture'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/certificates'
    | '/admin/communication'
    | '/admin/discipline'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/governance'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/procurement'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/'
    | '/admin'
    | '/apply'
    | '/events/$slug'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/admin/admissions/$id'
    | '/admin/admissions/settings'
    | '/admin/finance/payments'
    | '/admin/security/visitors'
    | '/apply/application/$id'
    | '/apply/status/$id'
    | '/admin/admissions'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/apply'
    | '/parent'
    | '/teacher'
    | '/_public/about'
    | '/_public/academics'
    | '/_public/admissions'
    | '/_public/contact'
    | '/_public/events'
    | '/_public/gallery'
    | '/_public/help'
    | '/_public/news'
    | '/_public/staff'
    | '/admin/academics'
    | '/admin/ai'
    | '/admin/architecture'
    | '/admin/attendance'
    | '/admin/calendar'
    | '/admin/certificates'
    | '/admin/communication'
    | '/admin/discipline'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/governance'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/procurement'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/_public/'
    | '/admin/'
    | '/apply/'
    | '/_public/events/$slug'
    | '/_public/gallery/$slug'
    | '/_public/news/$slug'
    | '/admin/admissions/$id'
    | '/admin/admissions/settings'
    | '/admin/finance/payments'
    | '/admin/security/visitors'
    | '/apply/application/$id'
    | '/apply/status/$id'
    | '/admin/admissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRouteWithChildren
  ParentRoute: typeof ParentRoute
  TeacherRoute: typeof TeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/academics': {
      id: '/_public/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof PublicAcademicsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/admissions': {
      id: '/_public/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof PublicAdmissionsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/help': {
      id: '/_public/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof PublicHelpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/news': {
      id: '/_public/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof PublicNewsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/staff': {
      id: '/_public/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof PublicStaffRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academics': {
      id: '/admin/academics'
      path: '/academics'
      fullPath: '/admin/academics'
      preLoaderRoute: typeof AdminAcademicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/architecture': {
      id: '/admin/architecture'
      path: '/architecture'
      fullPath: '/admin/architecture'
      preLoaderRoute: typeof AdminArchitectureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communication': {
      id: '/admin/communication'
      path: '/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discipline': {
      id: '/admin/discipline'
      path: '/discipline'
      fullPath: '/admin/discipline'
      preLoaderRoute: typeof AdminDisciplineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/governance': {
      id: '/admin/governance'
      path: '/governance'
      fullPath: '/admin/governance'
      preLoaderRoute: typeof AdminGovernanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/procurement': {
      id: '/admin/procurement'
      path: '/procurement'
      fullPath: '/admin/procurement'
      preLoaderRoute: typeof AdminProcurementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/_public/events/$slug': {
      id: '/_public/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof PublicEventsSlugRouteImport
      parentRoute: typeof PublicEventsRoute
    }
    '/_public/gallery/$slug': {
      id: '/_public/gallery/$slug'
      path: '/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof PublicGallerySlugRouteImport
      parentRoute: typeof PublicGalleryRoute
    }
    '/_public/news/$slug': {
      id: '/_public/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof PublicNewsSlugRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/admin/admissions/': {
      id: '/admin/admissions/'
      path: '/admissions'
      fullPath: '/admin/admissions/'
      preLoaderRoute: typeof AdminAdmissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions/$id': {
      id: '/admin/admissions/$id'
      path: '/admissions/$id'
      fullPath: '/admin/admissions/$id'
      preLoaderRoute: typeof AdminAdmissionsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions/settings': {
      id: '/admin/admissions/settings'
      path: '/admissions/settings'
      fullPath: '/admin/admissions/settings'
      preLoaderRoute: typeof AdminAdmissionsSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/payments': {
      id: '/admin/finance/payments'
      path: '/payments'
      fullPath: '/admin/finance/payments'
      preLoaderRoute: typeof AdminFinancePaymentsRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/security/visitors': {
      id: '/admin/security/visitors'
      path: '/security/visitors'
      fullPath: '/admin/security/visitors'
      preLoaderRoute: typeof AdminSecurityVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/apply/application/$id': {
      id: '/apply/application/$id'
      path: '/application/$id'
      fullPath: '/apply/application/$id'
      preLoaderRoute: typeof ApplyApplicationIdRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/status/$id': {
      id: '/apply/status/$id'
      path: '/status/$id'
      fullPath: '/apply/status/$id'
      preLoaderRoute: typeof ApplyStatusIdRouteImport
      parentRoute: typeof ApplyRoute
    }
  }
}

interface PublicEventsRouteChildren {
  PublicEventsSlugRoute: typeof PublicEventsSlugRoute
}

const PublicEventsRouteChildren: PublicEventsRouteChildren = {
  PublicEventsSlugRoute: PublicEventsSlugRoute,
}

const PublicEventsRouteWithChildren = PublicEventsRoute._addFileChildren(
  PublicEventsRouteChildren,
)

interface PublicGalleryRouteChildren {
  PublicGallerySlugRoute: typeof PublicGallerySlugRoute
}

const PublicGalleryRouteChildren: PublicGalleryRouteChildren = {
  PublicGallerySlugRoute: PublicGallerySlugRoute,
}

const PublicGalleryRouteWithChildren = PublicGalleryRoute._addFileChildren(
  PublicGalleryRouteChildren,
)

interface PublicNewsRouteChildren {
  PublicNewsSlugRoute: typeof PublicNewsSlugRoute
}

const PublicNewsRouteChildren: PublicNewsRouteChildren = {
  PublicNewsSlugRoute: PublicNewsSlugRoute,
}

const PublicNewsRouteWithChildren = PublicNewsRoute._addFileChildren(
  PublicNewsRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAcademicsRoute: typeof PublicAcademicsRoute
  PublicAdmissionsRoute: typeof PublicAdmissionsRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicEventsRoute: typeof PublicEventsRouteWithChildren
  PublicGalleryRoute: typeof PublicGalleryRouteWithChildren
  PublicHelpRoute: typeof PublicHelpRoute
  PublicNewsRoute: typeof PublicNewsRouteWithChildren
  PublicStaffRoute: typeof PublicStaffRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAcademicsRoute: PublicAcademicsRoute,
  PublicAdmissionsRoute: PublicAdmissionsRoute,
  PublicContactRoute: PublicContactRoute,
  PublicEventsRoute: PublicEventsRouteWithChildren,
  PublicGalleryRoute: PublicGalleryRouteWithChildren,
  PublicHelpRoute: PublicHelpRoute,
  PublicNewsRoute: PublicNewsRouteWithChildren,
  PublicStaffRoute: PublicStaffRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminFinanceRouteChildren {
  AdminFinancePaymentsRoute: typeof AdminFinancePaymentsRoute
}

const AdminFinanceRouteChildren: AdminFinanceRouteChildren = {
  AdminFinancePaymentsRoute: AdminFinancePaymentsRoute,
}

const AdminFinanceRouteWithChildren = AdminFinanceRoute._addFileChildren(
  AdminFinanceRouteChildren,
)

interface AdminRouteChildren {
  AdminAcademicsRoute: typeof AdminAcademicsRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminArchitectureRoute: typeof AdminArchitectureRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  AdminDisciplineRoute: typeof AdminDisciplineRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFinanceRoute: typeof AdminFinanceRouteWithChildren
  AdminGovernanceRoute: typeof AdminGovernanceRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminProcurementRoute: typeof AdminProcurementRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdmissionsIdRoute: typeof AdminAdmissionsIdRoute
  AdminAdmissionsSettingsRoute: typeof AdminAdmissionsSettingsRoute
  AdminSecurityVisitorsRoute: typeof AdminSecurityVisitorsRoute
  AdminAdmissionsIndexRoute: typeof AdminAdmissionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicsRoute: AdminAcademicsRoute,
  AdminAiRoute: AdminAiRoute,
  AdminArchitectureRoute: AdminArchitectureRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  AdminDisciplineRoute: AdminDisciplineRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFinanceRoute: AdminFinanceRouteWithChildren,
  AdminGovernanceRoute: AdminGovernanceRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminProcurementRoute: AdminProcurementRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdmissionsIdRoute: AdminAdmissionsIdRoute,
  AdminAdmissionsSettingsRoute: AdminAdmissionsSettingsRoute,
  AdminSecurityVisitorsRoute: AdminSecurityVisitorsRoute,
  AdminAdmissionsIndexRoute: AdminAdmissionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApplyRouteChildren {
  ApplyIndexRoute: typeof ApplyIndexRoute
  ApplyApplicationIdRoute: typeof ApplyApplicationIdRoute
  ApplyStatusIdRoute: typeof ApplyStatusIdRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyIndexRoute: ApplyIndexRoute,
  ApplyApplicationIdRoute: ApplyApplicationIdRoute,
  ApplyStatusIdRoute: ApplyStatusIdRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRouteWithChildren,
  ParentRoute: ParentRoute,
  TeacherRoute: TeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
