/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicAcademicsRouteImport } from './routes/_public.academics'
import { Route as PublicAdmissionsRouteImport } from './routes/_public.admissions'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicEventsRouteImport } from './routes/_public.events'
import { Route as PublicGalleryRouteImport } from './routes/_public.gallery'
import { Route as PublicNewsRouteImport } from './routes/_public.news'
import { Route as PublicStaffRouteImport } from './routes/_public.staff'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as PublicEventsSlugRouteImport } from './routes/_public.events.$slug'
import { Route as PublicGallerySlugRouteImport } from './routes/_public.gallery.$slug'
import { Route as PublicNewsSlugRouteImport } from './routes/_public.news.$slug'
import { Route as AdminAdmissionsIndexRouteImport } from './routes/admin.admissions.index'
import { Route as AdminAdmissionsIdRouteImport } from './routes/admin.admissions.$id'
import { Route as AdminAdmissionsSettingsRouteImport } from './routes/admin.admissions.settings'
import { Route as ApplyApplicationIdRouteImport } from './routes/apply.application.$id'
import { Route as ApplyStatusIdRouteImport } from './routes/apply.status.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAcademicsRoute = PublicAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAdmissionsRoute = PublicAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsRoute = PublicNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStaffRoute = PublicStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRoute,
} as any)
const PublicEventsSlugRoute = PublicEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicEventsRoute,
} as any)
const PublicGallerySlugRoute = PublicGallerySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicGalleryRoute,
} as any)
const PublicNewsSlugRoute = PublicNewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicNewsRoute,
} as any)
const AdminAdmissionsIndexRoute = AdminAdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsIdRoute = AdminAdmissionsIdRouteImport.update({
  id: '/admissions/$id',
  path: '/admissions/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsSettingsRoute = AdminAdmissionsSettingsRouteImport.update({
  id: '/admissions/settings',
  path: '/admissions/settings',
  getParentRoute: () => AdminRoute,
} as any)
const ApplyApplicationIdRoute = ApplyApplicationIdRouteImport.update({
  id: '/application/$id',
  path: '/application/$id',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyStatusIdRoute = ApplyStatusIdRouteImport.update({
  id: '/status/$id',
  path: '/status/$id',
  getParentRoute: () => ApplyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/academics': typeof PublicAcademicsRoute
  '/admissions': typeof PublicAdmissionsRoute
  '/contact': typeof PublicContactRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/gallery': typeof PublicGalleryRouteWithChildren
  '/news': typeof PublicNewsRouteWithChildren
  '/staff': typeof PublicStaffRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/events/$slug': typeof PublicEventsSlugRoute
  '/gallery/$slug': typeof PublicGallerySlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/admin/admissions/settings': typeof AdminAdmissionsSettingsRoute
  '/apply/application/$id': typeof ApplyApplicationIdRoute
  '/apply/status/$id': typeof ApplyStatusIdRoute
  '/admin/admissions/': typeof AdminAdmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/academics': typeof PublicAcademicsRoute
  '/admissions': typeof PublicAdmissionsRoute
  '/contact': typeof PublicContactRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/gallery': typeof PublicGalleryRouteWithChildren
  '/news': typeof PublicNewsRouteWithChildren
  '/staff': typeof PublicStaffRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/events/$slug': typeof PublicEventsSlugRoute
  '/gallery/$slug': typeof PublicGallerySlugRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/admin/admissions/settings': typeof AdminAdmissionsSettingsRoute
  '/apply/application/$id': typeof ApplyApplicationIdRoute
  '/apply/status/$id': typeof ApplyStatusIdRoute
  '/admin/admissions': typeof AdminAdmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/academics': typeof PublicAcademicsRoute
  '/_public/admissions': typeof PublicAdmissionsRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/events': typeof PublicEventsRouteWithChildren
  '/_public/gallery': typeof PublicGalleryRouteWithChildren
  '/_public/news': typeof PublicNewsRouteWithChildren
  '/_public/staff': typeof PublicStaffRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/_public/events/$slug': typeof PublicEventsSlugRoute
  '/_public/gallery/$slug': typeof PublicGallerySlugRoute
  '/_public/news/$slug': typeof PublicNewsSlugRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/admin/admissions/settings': typeof AdminAdmissionsSettingsRoute
  '/apply/application/$id': typeof ApplyApplicationIdRoute
  '/apply/status/$id': typeof ApplyStatusIdRoute
  '/admin/admissions/': typeof AdminAdmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/news'
    | '/staff'
    | '/admin/'
    | '/apply/'
    | '/events/$slug'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/admin/admissions/$id'
    | '/admin/admissions/settings'
    | '/apply/application/$id'
    | '/apply/status/$id'
    | '/admin/admissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/news'
    | '/staff'
    | '/'
    | '/admin'
    | '/apply'
    | '/events/$slug'
    | '/gallery/$slug'
    | '/news/$slug'
    | '/admin/admissions/$id'
    | '/admin/admissions/settings'
    | '/apply/application/$id'
    | '/apply/status/$id'
    | '/admin/admissions'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/apply'
    | '/_public/about'
    | '/_public/academics'
    | '/_public/admissions'
    | '/_public/contact'
    | '/_public/events'
    | '/_public/gallery'
    | '/_public/news'
    | '/_public/staff'
    | '/_public/'
    | '/admin/'
    | '/apply/'
    | '/_public/events/$slug'
    | '/_public/gallery/$slug'
    | '/_public/news/$slug'
    | '/admin/admissions/$id'
    | '/admin/admissions/settings'
    | '/apply/application/$id'
    | '/apply/status/$id'
    | '/admin/admissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/academics': {
      id: '/_public/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof PublicAcademicsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/admissions': {
      id: '/_public/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof PublicAdmissionsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/news': {
      id: '/_public/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof PublicNewsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/staff': {
      id: '/_public/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof PublicStaffRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/_public/events/$slug': {
      id: '/_public/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof PublicEventsSlugRouteImport
      parentRoute: typeof PublicEventsRoute
    }
    '/_public/gallery/$slug': {
      id: '/_public/gallery/$slug'
      path: '/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof PublicGallerySlugRouteImport
      parentRoute: typeof PublicGalleryRoute
    }
    '/_public/news/$slug': {
      id: '/_public/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof PublicNewsSlugRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/admin/admissions/': {
      id: '/admin/admissions/'
      path: '/admissions'
      fullPath: '/admin/admissions/'
      preLoaderRoute: typeof AdminAdmissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions/$id': {
      id: '/admin/admissions/$id'
      path: '/admissions/$id'
      fullPath: '/admin/admissions/$id'
      preLoaderRoute: typeof AdminAdmissionsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions/settings': {
      id: '/admin/admissions/settings'
      path: '/admissions/settings'
      fullPath: '/admin/admissions/settings'
      preLoaderRoute: typeof AdminAdmissionsSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/apply/application/$id': {
      id: '/apply/application/$id'
      path: '/application/$id'
      fullPath: '/apply/application/$id'
      preLoaderRoute: typeof ApplyApplicationIdRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/status/$id': {
      id: '/apply/status/$id'
      path: '/status/$id'
      fullPath: '/apply/status/$id'
      preLoaderRoute: typeof ApplyStatusIdRouteImport
      parentRoute: typeof ApplyRoute
    }
  }
}

interface PublicEventsRouteChildren {
  PublicEventsSlugRoute: typeof PublicEventsSlugRoute
}

const PublicEventsRouteChildren: PublicEventsRouteChildren = {
  PublicEventsSlugRoute: PublicEventsSlugRoute,
}

const PublicEventsRouteWithChildren = PublicEventsRoute._addFileChildren(
  PublicEventsRouteChildren,
)

interface PublicGalleryRouteChildren {
  PublicGallerySlugRoute: typeof PublicGallerySlugRoute
}

const PublicGalleryRouteChildren: PublicGalleryRouteChildren = {
  PublicGallerySlugRoute: PublicGallerySlugRoute,
}

const PublicGalleryRouteWithChildren = PublicGalleryRoute._addFileChildren(
  PublicGalleryRouteChildren,
)

interface PublicNewsRouteChildren {
  PublicNewsSlugRoute: typeof PublicNewsSlugRoute
}

const PublicNewsRouteChildren: PublicNewsRouteChildren = {
  PublicNewsSlugRoute: PublicNewsSlugRoute,
}

const PublicNewsRouteWithChildren = PublicNewsRoute._addFileChildren(
  PublicNewsRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAcademicsRoute: typeof PublicAcademicsRoute
  PublicAdmissionsRoute: typeof PublicAdmissionsRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicEventsRoute: typeof PublicEventsRouteWithChildren
  PublicGalleryRoute: typeof PublicGalleryRouteWithChildren
  PublicNewsRoute: typeof PublicNewsRouteWithChildren
  PublicStaffRoute: typeof PublicStaffRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAcademicsRoute: PublicAcademicsRoute,
  PublicAdmissionsRoute: PublicAdmissionsRoute,
  PublicContactRoute: PublicContactRoute,
  PublicEventsRoute: PublicEventsRouteWithChildren,
  PublicGalleryRoute: PublicGalleryRouteWithChildren,
  PublicNewsRoute: PublicNewsRouteWithChildren,
  PublicStaffRoute: PublicStaffRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdmissionsIdRoute: typeof AdminAdmissionsIdRoute
  AdminAdmissionsSettingsRoute: typeof AdminAdmissionsSettingsRoute
  AdminAdmissionsIndexRoute: typeof AdminAdmissionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAdmissionsIdRoute: AdminAdmissionsIdRoute,
  AdminAdmissionsSettingsRoute: AdminAdmissionsSettingsRoute,
  AdminAdmissionsIndexRoute: AdminAdmissionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApplyRouteChildren {
  ApplyIndexRoute: typeof ApplyIndexRoute
  ApplyApplicationIdRoute: typeof ApplyApplicationIdRoute
  ApplyStatusIdRoute: typeof ApplyStatusIdRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyIndexRoute: ApplyIndexRoute,
  ApplyApplicationIdRoute: ApplyApplicationIdRoute,
  ApplyStatusIdRoute: ApplyStatusIdRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
